//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------
using ProyectoPasteleria.Repositorio;
namespace ProyectoPasteleria.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Factura : Entidad
    {
        IRepositorio<Factura> _repositorio;
        public Factura()
        {
            _repositorio = new Repositorio<Factura>();
        }
        public HashSet<Factura> getFactura(int id) {
            return _repositorio.getFactura(id);
        }
        public int ID_FACTURA { get; set; }
        public int ID_PEDIDO { get; set; }
        public string URL_FACTURA { get; set; }
    
        public virtual Pedido Pedido { get; set; }
    }
}
