//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------
 using ProyectoPasteleria.Repositorio;
namespace ProyectoPasteleria.Models
{
    using System;
    using System.Collections.Generic;
   

    public partial class Pedido : Entidad
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        IRepositorio<Pedido> _repositorio;
        public Pedido()
        {
            _repositorio = new Repositorio<Pedido>();
        }
        public HashSet<Pedido> getPedidos(int id) {
            return _repositorio.getPedidos(id);
        }


        public int ID_PEDIDO { get; set; }
        public int ID_CLIENTE { get; set; }
        public int ID_PASTEL { get; set; }
        public decimal CANTIDAD { get; set; }
        public Nullable<decimal> TOTAL { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Factura> Factura { get; set; }
        public virtual Pastel Pastel { get; set; }
    }
}
